version: '3.3'

services:
  db:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'Password1'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'